export const POSTS_QUERY_KEY = ['posts']
export const PATHS_QUERY_KEY = ['path']
export const COMMENTS_QUERY_KEY = ['comments']
export const RESOURCES_QUERY_KEY = ['resources']
export const USERS_QUERY_KEY = ['users']
